### ISSUE TITLE
StartSounds in root are executed during parsing instead of playback

### ISSUE THREAD

**Issue by jchv** [lightspark/lightspark#364]
The issue template is enormous and full of things that are not terribly relevant, so apologies, skipping it for now :|

When you have an SWF that has sounds directly in frames via StartSound, Lightspark will play all of them as soon as they are parsed instead of during playback. This happens because of the following codepath:

```
(gdb) bt
#0  lightspark::StartSoundTag::play (this=this@entry=0x7fff9027b800, soundTag=soundTag@entry=0x7fff9023a480) at ./lightspark/src/parsing/tags.cpp:2083
#1  0x00007ffff7b1b106 in lightspark::StartSoundTag::execute (this=0x7fff9027b800, root=<optimized out>) at ./lightspark/src/parsing/tags.cpp:2079
#2  0x00007ffff7aacf1f in lightspark::ParseThread::parseSWF (this=this@entry=0xeb8a60, ver=...) at ./lightspark/src/swf.cpp:1585
#3  0x00007ffff7aadbc2 in lightspark::ParseThread::execute (this=0xeb8a60) at ./lightspark/src/swf.cpp:1404
#4  0x00007ffff7ac71aa in lightspark::ThreadPool::job_worker (th=0xe80620, index=<optimized out>) at ./lightspark/src/thread_pool.cpp:110
#5  0x00007ffff77cf96d in call_thread_entry_slot () from /nix/store/kl7x6mzy7wjvsnjmb7q7mi8bh5gjm9pv-glibmm-2.60.0/lib/libglibmm-2.4.so.1
#6  0x00007ffff6efab0d in g_thread_proxy () from /nix/store/9gvnlkyjabbhl26ijy4apv62dga430y5-glib-2.60.6/lib/libglib-2.0.so.0
#7  0x00007ffff7064ef7 in start_thread () from /nix/store/g88xj01xv7xzdx9dy2zwga0vk56fpfbm-glibc-2.27/lib/libpthread.so.0
#8  0x00007ffff731122f in clone () from /nix/store/g88xj01xv7xzdx9dy2zwga0vk56fpfbm-glibc-2.27/lib/libc.so.6
```

Demo SWF:

```
<?xml version="1.0" encoding="utf-8" ?>
<swf version="4" compressed="1">
  <Header framerate="1" frames="4">
    <size>
      <Rectangle left="0" right="3200" top="0" bottom="2400"/>
    </size>
    <tags>
      <FileAttributes hasMetaData="1" allowABC="1" suppressCrossDomainCaching="0" swfRelativeURLs="0" useNetwork="0"/>
      <ShowFrame/>
      <ShowFrame/>
      <ShowFrame/>
      <DefineSound objectID="1" format="2" rate="1" is16bit="1" stereo="0" samples="10064">
        <data><data>fQb/4yDAAAAAAlgBQAAA04HLWgYsDsgAUPAyg7W4GKCBYp3xFwv4F9PfYAIWDd4gGMz/bBuuFlYGMJAZ5IBnAH/4zDGhBzf//kDFbjjE6E4gQz//8XIOATuT6ZNjLjjFwf///k4gYEAIgf/jIMBbITPikAGUoAAHJ83JwuGgAw/////8UuRMXILkIgRNSBFyLlc0WmXP//////Lho6BoX0ygAAAIDxAABq8IJAxbBi2Oc3mRNeYl0x/WYkyZf5skZBqQLnWGsDm6wiCmPkiReMSK/+MgwDEYmrbEH5SIAJAVv9/9JL//9FH///0kltrRUkOgNXf9Q/Cof+XyAhtwgsYoE0USKkBSWXTIvF6VX/LAAAgABACoAAEUDAMrBlYMr////qZNH+H4U06YhApupan8pnDQqEYGAWj/4yDAKReL0tB/k2gAqUCiEh/KRomyeYqSU6//////8mjr/0zAy//P//5m6am3vdBkEl2V/pK///ysc4wDJ3//yQWAkFcJmZmQOQ5CAMfolgBgvJmrKNnWj7VVbX1bUq3W16K1KUk////jIMAlESs+uwHWaAH7TIYwCTARpKtSS/////////////////////1JF4F8kLbbbbZAAAqc5bJLZJbIqdd13VZToqdFbJLZJbJXWzruuynRU6KmSWj/qLIQRLKv/////////////////+MgwDsQoz6+WLTO2//////EIElAgAAAEkAAyc//////vZ6lqWgztqXuzo1qWpVMuDJgW8AuCGybnTIjVrV///+3///////////S////9nY+LhBTyQpdSFiAAAASQADJz/////9at2f/4yDAUxDrSo5QtSjZZNS1qRs9alLU1nZ3qKYbgCKmC14mVImxqhdn///////////////1////+paiyE0BDZPkkDDaqqqqqY4AAUcJzA1TUyamQW6C3QW6amTUyakEEU0EU1IprdBboP/jIMBqEOtGjlC1ZNm3QUyamTUya3QX/uaAvA1H0NX/////////////////////pgvMAOHbbbrAAD6ZF0MSUdkxYQs6fWFJj2vfww/P9c1z8/w/fVp0KaajRI0YvpoILTZNNBBadB0E/+MgwIESyz63GLta2RP+mmZhBJEXT//////////////////////WR5DBwAAAAJhAZ54M88Gef7r+37t/2W6etS9NTGROGRUJ/k2ARTAbT8tgCAwRy2TjuAEbA90cPfOfmxsgpnb//9//4yDAkBSbPrpZXpAD///////+3+r7/6H2/0SPBqvBEUKr//8mwoBAYCq//8yCBYCIWWwAAAAtQGKBgxQMGKB////X/0VUnoMt7lwuGilokOAMRAFktxngaKYBQFJpuM4AumgFCgo3V//jIMCYGLPWiIGVoACot/L5JpmiDJ9v9v/Q/////2/+/+n9v9X3/0CAAWBwCgWT//8lQKjsBoOFV//+TYDANAYDpgzQI3mZh2oABwP4/gY82JrGD/gUFO/tnVN3eP/zmO88Pzz7rDDF/+MgwJAau9qAgZaoAEgq7upBa2ZkVrW7u6lKrQ0/rRYpCzgFSBGpOqZSX////////////////////+6Q6ws0Tp6wFYf/7QAA0KUGsMFTCHzBlQM9360spN93lrLu8cfxx5+WX7xSoov/4yDAgBZDRp8Z35AAKSSqSSootSRZST1otRRb1qmZmM+EUYg1Na1/////////////////////9li/EADdgAAAAFLQGgAYi+DEXwYi////+3+Zk+Yk+YV1o+yai4bACQQUvrZI+A4SBf/jIMCCFdNGnvlfoAC582AWGBTmSZcNFIUGNVaVT/WnTvb//+1v////+rutdb3UglV1V/Uh9P/WagVNiAB5T//5NhYyFpLf/+ZAUJB65sAAAABgwDkAGKBhSgTgxQO/6T6fpf9S/Jsr/+MgwIUa29aEhZagAJBDU3RrRRWkk9BCNQBaMC2KiTIzwJzgDiXLANZAWYMDd0NAxRUii2f//1o6/////////0P03R+/qWipf2/1EwAaABQUb//+TIJkROjJf/8phYiFrLAAADSgJAD/4yDAdBtr1oCFlqAAARwABiL4MRfBiL/////X/ZaZoXz5VLdevc4CFUCJgkYnCOBvMCjXsGQwosRP/MTQ3dnSOsv/+ipS1XZv//+9aq////v/s1S1aF2RSWd+bVau6QFAwstL//ygFv/jIMBhGtvWhHeWoAC8I2Ps3//C9Y5iIAAAANUCKwAYi+DEXwYi/3/+9v9TfumpAihoTBOLqqS6IJ1B2UGTKgQfCgFJJJBFZA1t8ky4aOgykTVWr/0Kttqv//92W9b1////+r7/TeZ1/+MgwFAZe9aEhZaYAOv6NaJ0zDoRJW//9wxYY3b//YV4bSQAADtABAAUTdMAAxF8FIxmwFozj3k4ZEEN88bq9FNB7ekgmj63TUgT5gVicM7LUl1hBQ7Z4voEkLaIO0VpGLt8ly4tk7r/4yDARR2DhoR/logALJf/1W/ZJJ0V0v/6bpqZBbpqZB0V0rrXS/S/1f3WpBS0zP/1a1xXzD//6QrUiqTv6gArVVBqGeHJ1cY9BQQCkBLJIPmJfD3I12sDgFLFhxospT+99Q571Ke/vP/jIMAqE0g6d/PcAALwsp55l7z299rzx4leeYixhLYxGRJFZEgVKsEXkEcqvQV5VYA4S7MPrDOXU1A8NFFzLgYxcJMGEgKNjIyFAwtmDQGeVpYick+MI30IW2hyZVcpRkgbc9lpVZJd/+MgwDcQoLnkANvSbY3JRknYlVFVDV+qsCAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACD/4yDATwAAAlgAAAAAACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAA==</data></data>
      </DefineSound>
      <StartSound objectID="1" stopPlayback="0" noMultiple="0" hasEnvelope="0" hasLoop="0" hasOutPoint="0" hasInPoint="0"/>
      <End/>
    </tags>
  </Header>
</swf>
```
[Precompiled](https://github.com/lightspark/lightspark/files/3564600/sound-demo.swf.zip)

In Adobe Flash, the sound is played after around 3 seconds. In Lightspark, the sound is played immediately.

Taking a glance, I suspect that this is a design flaw that would require some rearchitecting. It looks like StartSounds nested deeper may not work at all. Unfortunately, it also breaks a boatload of varied old Flash content.

**Comment by jchv** [comment]
Thanks for fixing, it's good to see that it didn't require any major refactorings. (The DisplayListTag approach simply never occurred to me, but it seems very reasonable at first glance.)
