### ISSUE TITLE
segfault when clicking on file

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#371]
Opening the file from http://www.free-culture.tk/lessig-freeculture-loader.swf (after having downloaded it), I get a segmentation fault when I click on the presentation (full log attached [[fc-082.log](https://github.com/lightspark/lightspark/files/3682013/fc-082.log)]):

```
Thread 47 "lightspark" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffae914700 (LWP 14066)]
lightspark::ABCVm::getCurrentSecurityDomain (th=0x0)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/abc.cpp:2421
2421		return th->mi->context->root->securityDomain;
```

The backtrace is the following:

```
#0  0x00007ffff72f2df4 in lightspark::ABCVm::getCurrentSecurityDomain(lightspark::call_context*) (th=0x0)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/abc.cpp:2421
#1  0x00007ffff7415638 in lightspark::Loader::loadIntern(lightspark::URLRequest*, lightspark::LoaderContext*) (this=0x7fff743d8530, 
    r=0x7fff743d96b0, context=0x0)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/abc.h:1186
#2  0x00007ffff7614f05 in lightspark::AVM1MovieClipLoader::loadClip(lightspark::asAtom&, lightspark::SystemState*, lightspark::asAtom&, lightspark::asAtom*, unsigned int) (ret=..., sys=0x5555557c9230, obj=..., args=<optimized out>, argslen=<optimized out>)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/avm1/avm1display.cpp:97
#3  0x00007ffff762279a in lightspark::Function::call(lightspark::asAtom&, lightspark::asAtom&, lightspark::asAtom*, unsigned int) (num_args=2, args=0x7fffae911e50, obj=..., ret=..., this=<optimized out>)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/asobject.h:1097
#4  0x00007ffff762279a in lightspark::ACTIONRECORD::executeActions(lightspark::MovieClip*, lightspark::AVM1context*, std::vector<lightspark::ACTIONRECORD, std::allocator<lightspark::ACTIONRECORD> >&, std::map<unsigned int, lightspark::asAtom, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, lightspark::asAtom> > >&, lightspark::asAtom*, lightspark::asAtom*, lightspark::asAtom*, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > const&,---Type <return> to continue, or q <return> to quit---
 std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, bool, bool, bool, bool, bool, bool, bool, bool) (clip=0x7fff743cec80, context=<optimized out>, actionlist=..., scopevariables=..., result=<optimized out>, obj=<optimized out>, args=<optimized out>, num_args=<optimized out>, paramnames=..., paramregisternumbers=..., preloadParent=<optimized out>, preloadRoot=<optimized out>, suppressSuper=<optimized out>, preloadSuper=<optimized out>, suppressArguments=<optimized out>, preloadArguments=<optimized out>, suppressThis=<optimized out>, preloadThis=<optimized out>, preloadGlobal=<optimized out>)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/avm1_interpreter.cpp:1175
#5  0x00007ffff724e619 in lightspark::AVM1Function::call(lightspark::asAtom*, lightspark::asAtom*, lightspark::asAtom*, unsigned int) (num_args=0, args=0x0, obj=0x7fffae912d70, ret=0x7fffae912d68, this=<optimized out>)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/toplevel/toplevel.h:661
#6  0x00007ffff724e619 in lightspark::ASObject::AVM1HandleMouseEventStandard(lightspark::ASObject*, lightspark::MouseEvent*) (this=0x7fff743d0770, dispobj=<optimized out>, e=<optimized out>)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/asobject.cpp:1760
#7  0x00007ffff7400461 in lightspark::Stage::AVM1HandleEvent(lightspark::EventDispatcher*, lightspark::Ref<lightspark::Event>) (this=<optimized out>, dispatcher=0x555556200250, e=...)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/flash/display---Type <return> to continue, or q <return> to quit---
/flashdisplay.cpp:3493
#8  0x00007ffff72f479b in lightspark::ABCVm::publicHandleEvent(lightspark::EventDispatcher*, lightspark::Ref<lightspark::Event>) (dispatcher=0x555556200250, event=...) at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/smartrefs.h:59
#9  0x00007ffff7314f9e in lightspark::ABCVm::handleEvent(std::pair<lightspark::NullableRef<lightspark::EventDispatcher>, lightspark::Ref<lightspark::Event> >) (this=0x7fffc400d040, e={...})
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/smartrefs.h:59
#10 0x00007ffff7317db8 in lightspark::ABCVm::handleFrontEvent() (this=0x7fffc400d040) at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/smartrefs.h:59
#11 0x00007ffff7318393 in lightspark::ABCVm::Run(lightspark::ABCVm*) (th=0x7fffc400d040)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/scripting/abc.cpp:2269
#12 0x00007ffff6b8ef92 in sigc::slot0<void>::operator()() const (this=0x7fffbc000f80) at threads.cc:77
#13 0x00007ffff6b8ef92 in call_thread_entry_slot (data=0x7fffbc000f80)
    at threads.cc:64
#14 0x00007ffff50cf01a in g_thread_proxy (data=0x7fffd020ea80) at gthread.c:784
#15 0x00007ffff5a20594 in start_thread () at /lib64/libpthread.so.0
#16 0x00007ffff62cde5f in clone () at /lib64/libc.so.6
```

**Comment by ousia** [comment]
Many thanks for your fix, @dbluelle.
