### ISSUE TITLE
segfault when opening file

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#372]
[I don’t know whether this issue might be a duplicate of #371.]

After downloading http://www.mejorar-presentaciones.tk/mejorar-presentaciones-loader.swf, I get a segmentation fault when I open the file.

Here is the backtrace:

```
#0  0x00007ffff726fcb0 in lightspark::ParseThread::parseSWF(lightspark::UI8) (this=0x55555620b040, ver=...)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/swftypes.h:786
#1  0x00007ffff72706c2 in lightspark::ParseThread::execute() (this=0x55555620b040) at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/swf.cpp:1402
#2  0x00007ffff7289b43 in lightspark::ThreadPool::job_worker(lightspark::ThreadPool*, unsigned int) (th=0x5555561d1bd0, index=<optimized out>)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/thread_pool.cpp:110
#3  0x00007ffff6b8ef92 in sigc::slot0<void>::operator()() const (this=0x5555557c88f0) at threads.cc:77
#4  0x00007ffff6b8ef92 in call_thread_entry_slot (data=0x5555557c88f0) at threads.cc:64
#5  0x00007ffff50cf01a in g_thread_proxy (data=0x5555557c4850) at gthread.c:784
#6  0x00007ffff5a20594 in start_thread (arg=<optimized out>) at pthread_create.c:463
#7  0x00007ffff62cde5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

And here is the log:

```
[New Thread 0x7fffd604e700 (LWP 14534)]
[New Thread 0x7fffcd7d5700 (LWP 14535)]
[New Thread 0x7fffccfd4700 (LWP 14536)]
[New Thread 0x7fffc7fff700 (LWP 14537)]
[New Thread 0x7fffc77fe700 (LWP 14538)]
[New Thread 0x7fffc6ffd700 (LWP 14539)]
[New Thread 0x7fffc67fc700 (LWP 14540)]
[New Thread 0x7fffc5ffb700 (LWP 14541)]
[New Thread 0x7fffc57fa700 (LWP 14542)]
[New Thread 0x7fffc4ff9700 (LWP 14543)]
[New Thread 0x7fffbffff700 (LWP 14544)]
[New Thread 0x7fffbf7fe700 (LWP 14545)]
[New Thread 0x7fffbeffd700 (LWP 14546)]
[New Thread 0x7fffbe7fc700 (LWP 14547)]
[New Thread 0x7fffbdffb700 (LWP 14548)]
[New Thread 0x7fffbd7fa700 (LWP 14549)]
[New Thread 0x7fffbcff9700 (LWP 14550)]
[New Thread 0x7fffbc7f8700 (LWP 14551)]
[New Thread 0x7fffbbff7700 (LWP 14552)]
[New Thread 0x7fffbb7f6700 (LWP 14553)]
[New Thread 0x7fffbaff5700 (LWP 14554)]
[New Thread 0x7fffba7f4700 (LWP 14555)]
[New Thread 0x7fffb9ff3700 (LWP 14556)]
[New Thread 0x7fffb97f2700 (LWP 14557)]
[New Thread 0x7fffb8ff1700 (LWP 14558)]
[New Thread 0x7fffb3fff700 (LWP 14559)]
[New Thread 0x7fffb37fe700 (LWP 14560)]
[New Thread 0x7fffb2ffd700 (LWP 14561)]
[New Thread 0x7fffb27fc700 (LWP 14562)]
[New Thread 0x7fffb1ffb700 (LWP 14563)]
[New Thread 0x7fffb17fa700 (LWP 14564)]
[New Thread 0x7fffb0ff9700 (LWP 14565)]
[New Thread 0x7fffb07f8700 (LWP 14566)]
[New Thread 0x7fffafff7700 (LWP 14567)]
[New Thread 0x7fffaf7f6700 (LWP 14568)]
[New Thread 0x7fffaeff5700 (LWP 14569)]
[New Thread 0x7fffae7f4700 (LWP 14570)]
[New Thread 0x7fffadff3700 (LWP 14571)]
[New Thread 0x7fffad7f2700 (LWP 14572)]
[New Thread 0x7fffacff1700 (LWP 14573)]
[New Thread 0x7fffac7f0700 (LWP 14574)]
[New Thread 0x7fffabfef700 (LWP 14575)]
[New Thread 0x7fffab7ee700 (LWP 14576)]
NOT_IMPLEMENTED: LoaderInfo: childAllowsParent and parentAllowsChild always return true
INFO: RenderThread this=0x55555620a970
INFO: Creating input thread
INFO: Running in local-with-filesystem sandbox
INFO: zlib compressed SWF file: Version 8
INFO: FrameRate 12
TRACE: Reading tag type: 9 at byte 15 with length 3 bytes
ERROR: Invalid SWF - First tag must be a FileAttributesTag!

Thread 3 "lightspark" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcd7d5700 (LWP 14535)]
lightspark::ParseThread::parseSWF(lightspark::UI8) () at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/swftypes.h:786
786			return buf;
```

**Comment by ousia** [comment]
@dbluelle, many thanks for the fix.
