### ISSUE TITLE
segfault with attached SWF

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#407]
@dbluelle 

this file [a.swf.txt](https://github.com/lightspark/lightspark/files/3982251/a.swf.txt) segfaults LS.

Error message (already in `gdb`):

```
[New Thread 0x7fffa5ff3700 (LWP 2808)]

(process:2759): glibmm-ERROR **: 08:34:45.731: 
unhandled exception (type std::exception) in signal handler:
what: std::bad_alloc
```

Backtrace:

```
#0  0x00007ffff50a48e5 in _g_log_abort (breakpoint=1) at gmessages.c:580
#1  0x00007ffff50a59b1 in g_log_default_handler (log_domain=log_domain@entry=0x7ffff6b9e56f "glibmm", log_level=log_level@entry=6, message=message@entry=0x7fff6c1d41d0 "\nunhandled exception (type std::exception) in signal handler:\nwhat: std::bad_alloc\n", unused_data=unused_data@entry=0x0) at gmessages.c:3158
#2  0x00007ffff50a5bff in g_logv (log_domain=0x7ffff6b9e56f "glibmm", log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=args@entry=0x7fffa5ff2760)
    at gmessages.c:1370
#3  0x00007ffff50a5df3 in g_log (log_domain=log_domain@entry=0x7ffff6b9e56f "glibmm", log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x7ffff6b9fe28 "\nunhandled exception (type std::exception) in signal handler:\nwhat: %s\n") at gmessages.c:1432
#4  0x00007ffff6b76642 in (anonymous namespace)::glibmm_unexpected_exception () at exceptionhandler.cc:73
#5  0x00007ffff6b76642 in Glib::exception_handlers_invoke() () at exceptionhandler.cc:167
#6  0x00007ffff6b75c33 in (anonymous namespace)::call_thread_entry_slot(void*) (data=0x7fffc0000f80) at threads.cc:73
#7  0x00007ffff50c701a in g_thread_proxy (data=0x7fffd0264280) at gthread.c:784
#8  0x00007ffff5a18594 in start_thread (arg=<optimized out>) at pthread_create.c:463
#9  0x00007ffff62c5e5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I was trying to report a rendering issue, but the file generated for it segfaults LS 😅.

Many thanks for your help.

**Comment by ousia** [comment]
@dbluelle,

I wonder whether this might be related: ruffle-rs/ruffle#184.

The issue that I wanted to report was about glyph display.
