### ISSUE TITLE
wrong size with screenshots in fullscreen

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#427]
@dbluelle,

testing the new screenshot feature, I noticed that screenshots in fullscreen are taken with size from the standard window (or the resized one), but with full screen dimensions.

Could you fix this? Many thanks for your excellent work and your help.

**Comment by dbluelle** [comment]
Hmm, I couldn't reproduce this.
Whenever I create a screenshot in fullscreen mode, it's exactly the size of my screen.
Do you have a reproducible case?

**Comment by ousia** [comment]
@dbluelle,

playing locally https://www.improve-presentations.tk/Presentacion-loader.swf (with https://www.improve-presentations.tk/Presentacion-loader.swf located on the same directory), I get a segfault when I:

1. Start playing the presentation.
1. Take a screenshot from each number at full screen (Ctrl+O).
1. Presentation never reached number 3 in my tests.

Error message:

```
Thread 9 "lightspark" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc6ffd700 (LWP 18153)]
_int_malloc (av=av@entry=0x7fff64000020, bytes=bytes@entry=202920)
    at malloc.c:4108
4108	          set_head (remainder, remainder_size | PREV_INUSE);
```

Backtrace:

```
#0  0x00007ffff634e191 in _int_malloc (av=av@entry=0x7fff64000020, bytes=bytes@entry=202920) at malloc.c:4108
#1  0x00007ffff634f4fa in __GI___libc_malloc (bytes=202920) at malloc.c:3073
#2  0x00007ffff69347bc in operator new(unsigned long) (sz=202920) at ../../../../libstdc++-v3/libsupc++/new_op.cc:50
#3  0x00007ffff6934869 in operator new[](unsigned long) (sz=<optimized out>) at ../../../../libstdc++-v3/libsupc++/new_opv.cc:32
#4  0x00007ffff76b7198 in lightspark::CairoRenderer::allocateSurface(unsigned char*&) (this=0x7fff702dfc80, buf=@0x7fffc6ffc5e0: 0x0)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/backends/graphics.cpp:515
#5  0x00007ffff76b7386 in lightspark::CairoRenderer::getPixelBuffer() (this=0x7fff702dfc80)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/backends/graphics.cpp:591
#6  0x00007ffff76b5582 in lightspark::AsyncDrawJob::execute() (this=0x7fff7023ea40) at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/backends/graphics.cpp:1016
#7  0x00007ffff769e273 in lightspark::ThreadPool::job_worker(lightspark::ThreadPool*, unsigned int) (th=0x5555568a87e0, index=<optimized out>)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/thread_pool.cpp:110
#8  0x00007ffff6f9df92 in sigc::slot0<void>::operator()() const (this=0x5555557ddb10) at threads.cc:77
#9  0x00007ffff6f9df92 in call_thread_entry_slot (data=0x5555557ddb10) at threads.cc:64
#10 0x00007ffff6ca801a in g_thread_proxy (data=0x5555557c4e30) at gthread.c:784
#11 0x00007ffff17be594 in start_thread (arg=<optimized out>) at pthread_create.c:463
#12 0x00007ffff63c4e5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I hope it helps.
