### ISSUE TITLE
new Ctrl+S segfaults LS

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#430]
@dbluelle,

many thanks for your latest commits.

I’m afraid that taking a screenshot (Ctrl+S) from https://www.improve-presentations.tk/Presentacion-presentation.swf (loaded locally) segfaults LS:

Error message:

```
free(): invalid next size (normal)

Thread 46 "lightspark" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffa27fc700 (LWP 8956)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
```

And backtrace:

```
#0  0x00007ffff6301efb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff62ec5b9 in __GI_abort () at abort.c:79
#2  0x00007ffff63447b7 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff644e1ac "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff634ac0c in malloc_printerr (str=str@entry=0x7ffff644fee0 "free(): invalid next size (normal)") at malloc.c:5337
#4  0x00007ffff634c5d4 in _int_free (av=0x7fff64000020, p=0x7fff65a5df50, have_lock=<optimized out>) at malloc.c:4314
#5  0x00007ffff76c5f82 in lightspark::RenderThread::generateScreenshot() (this=0x5555568ea560)
    at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/backends/rendering.cpp:322
#6  0x00007ffff76c9228 in lightspark::RenderThread::doRender(lightspark::ThreadProfile*, lightspark::Chronometer*) (this=0x5555568ea560, profile=0x7fff65a59b30, chronometer=0x7fffa27fb688) at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/backends/rendering.cpp:271
#7  0x00007ffff76c9e06 in lightspark::RenderThread::worker() (this=0x5555568ea560) at /usr/src/debug/lightspark-0.8.2-1.fc28.x86_64/src/backends/rendering.cpp:183
#8  0x00007ffff6f9df92 in sigc::slot0<void>::operator()() const (this=0x7fffd035bc20) at threads.cc:77
#9  0x00007ffff6f9df92 in call_thread_entry_slot (data=0x7fffd035bc20) at threads.cc:64
#10 0x00007ffff6ca801a in g_thread_proxy (data=0x7fffd0232c00) at gthread.c:784
#11 0x00007ffff17be594 in start_thread (arg=<optimized out>) at pthread_create.c:463
#12 0x00007ffff63c4e5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Many thanks for your help.

**Comment by eiglow** [comment]
This seems to only be present in this specific swf, I tried a few others and they didn't present this issue.

**Comment by ousia** [comment]
@eiglow, many thanks for your testing.

I’m reporting it, since I think LS follows a strict no–crashes policy.

But it is up to @dbluelle to fix it.

**Comment by ousia** [comment]
@dbluelle, I still haven’t checked it, but many thanks for your fix.
