### ISSUE TITLE
[regression?] loader segfaults LS

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#894]
> @dbluelle, I have the impression I already reported this. I think it might be a regression.
> Many thanks for your help.

### What is the purpose of your issue?
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

1. https://free-culture.tk/lfc-loader.swf.
2. https://free-culture.tk/lfc-presentation.swf.

#### Provide the complete set of instructions required to reproduce the problem:

1. Download both files.
2. Run `lightspark lfc-loader.swf`.
3. Click on the screen.
4. You get a segfault.

#### What kind of failure is your issue?

- [x] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``

Error message and backtrace:

```
Thread 47 "ABCVm" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff2d7fa700 (LWP 31892)]
lightspark::RefCountable::decRef (this=0x2f2f2f3a656c6966) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/smartrefs.h:82
82			if (!isConstant && !cached)
(gdb) bt
#0  0x00007ffff749aed4 in lightspark::RefCountable::decRef() (this=0x2f2f2f3a656c6966) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/smartrefs.h:82
#1  0x00007ffff7706018 in lightspark::NullableRef<lightspark::AVM1MovieClipLoader>::operator=<lightspark::AVM1MovieClipLoader>(lightspark::Ref<lightspark::AVM1MovieClipLoader> const&) (r=..., this=0x555555849b28) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/smartrefs.h:59
#2  0x00007ffff7706018 in lightspark::MovieClip::AVM1LoadMovie(lightspark::asAtom&, lightspark::SystemState*, lightspark::asAtom&, lightspark::asAtom*, unsigned int) (ret=..., sys=<optimized out>, obj=..., args=<optimized out>, argslen=<optimized out>)
    at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/scripting/flash/display/flashdisplay.cpp:2410
#3  0x00007ffff7983f65 in lightspark::Function::call(lightspark::asAtom&, lightspark::asAtom&, lightspark::asAtom*, unsigned int) (num_args=<optimized out>, args=0x7fff2d7f7d70, obj=..., ret=..., this=<optimized out>) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/asobject.h:1160
#4  0x00007ffff7983f65 in lightspark::ACTIONRECORD::executeActions(lightspark::DisplayObject*, lightspark::AVM1context*, std::vector<unsigned char, std::allocator<unsigned char> > const&, unsigned int, std::map<unsigned int, lightspark::asAtom, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, lightspark::asAtom> > >&, lightspark::asAtom*, lightspark::asAtom*, lightspark::asAtom*, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, bool, bool, bool, bool, bool, bool, bool, bool, lightspark::AVM1Function*, lightspark::AVM1Function*, lightspark::Activation_object*, lightspark::asAtom*) (clip=0x5555558495b0, context=<optimized out>, actionlist=..., startactionpos=<optimized out>, scopevariables=..., result=<optimized out>, obj=<optimized out>, args=<optimized out>, num_args=<optimized out>, paramnames=..., paramregisternumbers=..., preloadParent=<optimized out>, preloadRoot=<optimized out>, suppressSuper=<optimized out>, preloadSuper=<optimized out>, suppressArguments=<optimized out>, preloadArguments=<optimized out>, suppressThis=<optimized out>, preloadThis=<optimized out>, preloadGlobal=<optimized out>, caller=<optimized out>, callee=<optimized out>, actobj=<optimized out>, superobj=<optimized out>)
    at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/scripting/avm1_interpreter.cpp:1718
#5  0x00007ffff770cc7f in lightspark::SimpleButton::AVM1HandleMouseEvent(lightspark::EventDispatcher*, lightspark::MouseEvent*) (this=0x7fff841c9c30, dispatcher=<optimized out>, e=0x7fffd026add0) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/scripting/flash/display/flashdisplay.h:540
#6  0x00007ffff76ea9b0 in lightspark::Stage::AVM1HandleEvent(lightspark::EventDispatcher*, lightspark::Event*) (this=<optimized out>, dispatcher=0x7fff841c9c30, e=0x7fffd026add0) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/scripting/flash/display/flashdisplay.cpp:3960
#7  0x00007ffff754d948 in lightspark::ABCVm::publicHandleEvent(lightspark::EventDispatcher*, lightspark::Ref<lightspark::Event>) (dispatcher=0x7fff841c9c30, event=...)
    at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/asobject.h:1160
#8  0x00007ffff7555c2e in lightspark::ABCVm::handleEvent(std::pair<lightspark::NullableRef<lightspark::EventDispatcher>, lightspark::Ref<lightspark::Event> >) (this=0x7fffc800d0b0, e={...}) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/smartrefs.h:59
#9  0x00007ffff7557a9b in lightspark::ABCVm::handleFrontEvent() (this=0x7fffc800d0b0) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/smartrefs.h:59
#10 0x00007ffff7557fa0 in lightspark::ABCVm::Run(void*) (d=0x7fffc800d0b0) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/scripting/abc.cpp:1863
#11 0x00007ffff6ffdb20 in SDL_RunThread (data=0x7fffc00011f0) at /usr/src/debug/SDL2-2.0.9-1.fc28.x86_64/src/thread/SDL_thread.c:283
#12 0x00007ffff70754bd in RunThread (data=<optimized out>) at /usr/src/debug/SDL2-2.0.9-1.fc28.x86_64/src/thread/pthread/SDL_systhread.c:78
#13 0x00007ffff1c81594 in start_thread (arg=<optimized out>) at pthread_create.c:463
#14 0x00007ffff640fe5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Provide the Lightspark version

Output of ``lightspark -v``:

```
0.8.5-1354-gccf81a45
```

#### What operating system are you are running on?

- [x] Linux: _Fedora_.

#### How are you are running Lightspark?

- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)

**Comment by ousia** [comment]
@dbluelle, I’m afraid it isn’t fixed (because I get a new error).

I get two error messages after loading the loader:

```
ERROR: AVM1:8 no MovieClip for ActionStop [object SimpleButton](0x7f73001c6a00 / 5) tag=8
ERROR: AVM1:2 no MovieClip for ActionStop [object TextField](0x7f73001c7130 / 10) tag=2 "";0x0  0.00
```

Backtrace reads:

```
Thread 47 "ABCVm" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff2d7fa700 (LWP 15971)]
lightspark::RefCountable::decRef (this=0x2f2f2f3a656c6966) at /usr/src/debug/lightspark-0.8.3-1.fc28.x86_64/src/smartrefs.h:82
82			if (!isConstant && !cached)
```

**Comment by ousia** [comment]
Many thanks for your help and you work.

**Comment by dbluelle** [comment]
OK, I've used the wrong version of the loader for my tests...
It's _really_ fixed now.

**Comment by ousia** [comment]
Many thanks for the fix, @dbluelle.

Loader works fine now. I’m afraid I discovered other issues.

Many thanks again for your work and your patience.
