### ISSUE TITLE
SWF file goes to 100% CPU

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#929]
### What is the purpose of your issue?
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

The attached file [steamboat.swf.txt](https://github.com/lightspark/lightspark/files/8405073/steamboat.swf.txt) is a Flash file.

`.txt` extension added to allow GitHub upload.

#### Provide the complete set of instructions required to reproduce the problem:

1. Run `lightspark steamboat.swf`.
2. `ERROR: AVM1: ActionSetTarget clip not found:movie`.
3. Lightspark goes to 100% CPU and becomes unresponsive.

#### What kind of failure is your issue?

- [X] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1446-gce52b1dd
```

#### What operating system are you are running on?

- [X] Linux: *Fedora 35*

#### How are you are running Lightspark?

- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)

I hope I can paste it after debug info is completely downloaded.

**Comment by ousia** [comment]
@dbluelle,

I get the backtrace when I quit unresponsive Lightspark:

```
#0  __futex_abstimed_wait_common64
    (private=128, cancel=true, abstime=0x0, op=265, expected=23985, futex_word=0x7fff3aff5910) at futex-internal.c:57
#1  __futex_abstimed_wait_common
    (futex_word=futex_word@entry=0x7fff3aff5910, expected=23985, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff6ff879f in __GI___futex_abstimed_wait_cancelable64
    (futex_word=futex_word@entry=0x7fff3aff5910, expected=<optimized out>, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128)
    at futex-internal.c:139
#3  0x00007ffff6ffd624 in __pthread_clockjoin_ex
    (threadid=140734183200320, thread_return=thread_return@entry=0x0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, block=block@entry=true)
    at pthread_join_common.c:105
#4  0x00007ffff6ffd4c3 in ___pthread_join
    (threadid=<optimized out>, thread_return=thread_return@entry=0x0)
    at pthread_join.c:25
#5  0x00007ffff756c100 in SDL_SYS_WaitThread
    (thread=<optimized out>, thread=0x7fffb0000ef0)
    at /usr/src/debug/SDL2-2.0.20-1.fc35.x86_64/src/thread/pthread/SDL_systhread.c:289
#6  SDL_WaitThread_REAL (status=0x0, thread=0x7fffb0000ef0)
    at /usr/src/debug/SDL2-2.0.20-1.fc35.x86_64/src/thread/SDL_thread.c:433
#7  SDL_WaitThread_REAL (thread=0x7fffb0000ef0, status=0x0)
    at /usr/src/debug/SDL2-2.0.20-1.fc35.x86_64/src/thread/SDL_thread.c:430
#8  0x00007ffff79620ee in lightspark::ABCVm::shutdown() (this=0x7fffb800d0d0)
    at /usr/src/debug/lightspark-0.8.6-1.fc35.x86_64/src/scripting/abc.cpp:770
#9  lightspark::ABCVm::shutdown() (this=0x7fffb800d0d0)
    at /usr/src/debug/lightspark-0.8.6-1.fc35.x86_64/src/scripting/abc.cpp:760
#10 0x00007ffff78c83fa in lightspark::SystemState::destroy()
    (this=0x5555555dda00)
    at /usr/src/debug/lightspark-0.8.6-1.fc35.x86_64/src/swf.cpp:681
#11 0x000055555555cd9d in main(int, char**)
    (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/lightspark-0.8.6-1.fc35.x86_64/src/main.cpp:582
```

Before that, I get the following message when quitting Lightspark pressing Ctrl+C on the terminal running GDB:

```

Thread 1 "lightspark" received signal SIGINT, Interrupt.
__futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=23985, futex_word=0x7fff3aff5910) at futex-internal.c:57
57	    return INTERNAL_SYSCALL_CANCEL (futex_time64, futex_word, op, expected,
```

I hope it may be useful.

Many thanks for your help.
